### ISSUE TITLE
"build.gradle" needs to be updated for Gradle 0.9 format

### ISSUE THREAD

**Issue by huhx0015** [strongloop/loopback-android-getting-started#12]
I've noticed that the build.gradle is out of date and needs to be updated to Gradle 0.9+ format. Changes that need to be made include:

instrumentTest.setRoot('tests') -> androidTest.setRoot('tests')

**Comment by loay** [comment]
The current version is 2.10. 
Need to review `build.gradle` to ensure that it is conform with our code.

**Comment by loay** [comment]
connect to: https://github.com/strongloop/loopback-android-getting-started/pull/16

**Comment by bajtos** [comment]
> loay commented 7 hours ago
> connect to: #16

You need to create the connection from the pull request, not the issue. I have updated the PR description, please note that the syntax is `Connect to #id` (no colon).
