### ISSUE TITLE
Cannot use createUser

### ISSUE THREAD

**Issue by cingolanifede** [strongloop/loopback-android-getting-started#24]
Hi, I am developing an app and I am not able to use this:
User user = userRepo.createUser("name@example.com", "password");

Is the correct way to use it? I can make the login but cant create users that way?
Thanks

**Comment by b-admike** [comment]
Hi @cingolanifede, According to https://loopback.io/doc/en/lb2/Android-SDK.html, I think it does create a user for you if you follow the steps in the tutorial (it extends the LoopBack base User model). Can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report. For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by b-admike** [comment]
Closing this ticket. @cingolanifede If you are still experiencing this issue, feel free to re-open this issue with more info and we can investigate further.
